import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import tasksRouter from "./tasks";
import responsesRouter from "./responses";
import datasetsRouter from "./datasets";
import adsRouter from "./ads";
import rewardsRouter from "./rewards";
import leaderboardRouter from "./leaderboard";
import analyticsRouter from "./analytics";
import clientsRouter from "./clients";
import authRouter from "./auth";
import adminRouter from "./admin";
import referralRouter from "./referral";
import telegramRouter from "./telegram";
import exportRouter from "./export";
import uploadRouter from "./upload";
import otpRouter from "./otp";
import statsRouter from "./stats";
import stripeRouter from "./stripe";
import agentRouter from "./agent";
import chatRouter from "./chat";
import contactRouter from "./contact";

const router: IRouter = Router();

router.use(healthRouter);
router.use(statsRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(tasksRouter);
router.use(responsesRouter);
router.use(datasetsRouter);
router.use(adsRouter);
router.use(rewardsRouter);
router.use(leaderboardRouter);
router.use(analyticsRouter);
router.use(clientsRouter);
router.use(adminRouter);
router.use(referralRouter);
router.use(telegramRouter);
router.use(exportRouter);
router.use(uploadRouter);
router.use(otpRouter);
router.use(stripeRouter);
router.use(agentRouter);
router.use(chatRouter);
router.use(contactRouter);

export default router;
